### PR TITLE
Api completion & parametrized XML tests

### PR DESCRIPTION
**Pull request by ml31415**
- Added XML API specification
- Added parametrized tests for API completeness
- Fixed found issues

### CODE REVIEW

**Comment by limx0** [comment]
Thanks @ml31415 - A couple of tests failing on 3.9 but can fix on develop.

**Comment by ml31415** [comment]
Thanks for merging. Well, how attached are you to 3.9 support? The parser makes heavy use of the typing, including internals of their implementation. As it turns out, there were some changes under the hood between 3.9 and 3.10, that now create that issue. 3.10 is the standard even in most distros now I guess. Also there is nothing stopping someone from moving from 3.9 to 3.10, as it was with py2 to py3. I'd be totally fine with supporting 3.10+ only.

**Comment by ml31415** [comment]
Just checked https://peps.python.org/pep-0693/ py3.12 seems to be upcoming this summer, so that would probably replace 3.9 within the supported versions within a few months.

**Comment by limx0** [comment]
3.9 doesn't hit EOL for another 2+ years (https://endoflife.date/python) so I think it's a reasonable thing to strive for.

**Comment by ml31415** [comment]
Alright, I'll see if there is a quick fix.

I'm personally a big fan of staying backwards compatible, if it's feasible and no extra burden. `numpy_groupies` e.g. still runs even with py2. But this project seems to me "fresh" enough, to not compromise too much with backwards compatibility. E.g. not using the newer pipe syntax for type unions. Or not to have to add some version forks for py3.9 for outdated typing internals. I'd rather have this lib using state of the art python, in order to avoid technical debt, that someone needs to clean up later on - and this *someone* possibly being me. So as long as you're not personally using it with py3.9, and no one else comes up and complains, I wouldn't bother too much about it. And if someone complains, py3.9 could easily be readded.

**Pull request merged**
