### PR TITLE
WIP: API completion and refactoring

### PR DESCRIPTION
**Pull request by ml31415**
- Refactored `spec` more to how betfair structures the API
- Added most type definitions and enums from the API, methods still missing
- Using msgspec 0.15 generic structs for API responses
- Added `FloatStr` and `IntStr` and according hooks for dealing with betfairs inconsistent quotation usage

### CODE REVIEW

**Comment by limx0** [comment]
Hey @ml31415, thanks for this awesome PR! It LGTM. 

> I was trying to make all the API definition a bit less verbose. E.g. all those frozen=True are redundant, as it's inherited anyways. Unfortunatly mypy complains, when I remove it. Also all those Optional[...] = None are rather unelegant. Feel free to join the discussion about it here:

Yeah I ran into the same issues, not really too fussed though given the API is unlikely to change much.

**Comment by ml31415** [comment]
Oh, that was quick. More changes to come soon.

Do you have any better ideas for `IntStr` or `FloatStr`? The ugly thing about them is, that it requires encoding and decoding hooks to be set. And also, that they leave an `IntStr` object in the end, where there should better be a plain `int`. Another downside, further restricting the values with annotations, like enforcing positive ints doesn't work anymore.

**Comment by limx0** [comment]
> Oh, that was quick. More changes to come soon.

No problem - happy to merge them as they come. 

> Do you have any better ideas for IntStr or FloatStr?

Not especially; I don't think theres much we can do because they're encoded incorrectly by Betfair. Agreed the `IntStr/FloatStr` types are a little ugly but they're better than parsing the strings, so happy to keep them until/if we find something better.

**Comment by limx0** [comment]
One thing I will change however is the Union syntax - I'm keen to support python 3.9 for now. 

I've opened https://github.com/limx0/betfair_parser/pull/9 to add it into CI and fix the union type defs

**Pull request merged**
