### PR TITLE
Add support for py3.12

### PR DESCRIPTION
**Pull request by ml31415**

### CODE REVIEW

**Comment by ml31415** [comment]
Looks like `pycln` needs an update first.

**Comment by hadialqattan** [comment]
> Looks like `pycln` needs an update first. I opened an issue there. [hadialqattan/pycln#219](https://github.com/hadialqattan/pycln/issues/219)

Hi, kindly, upgrade to pycln v2.3.0; it contains the fix.

**Comment by limx0** [comment]
Thanks @ml31415 and @hadialqattan !

**Comment by limx0** [comment]
@hadialqattan any ideas why this might be happening? 

https://github.com/limx0/betfair_parser/actions/runs/6529781721/job/17727966092

**Comment by ml31415** [comment]
I'm a bit surprised that it worked for you in 3.12. I suppose it's another issue with `pycln` and 3.12, see here: https://github.com/hadialqattan/pycln/issues/219#issuecomment-1763450260

**Comment by limx0** [comment]
I think its because my `precommit` install is a 3.10 env, but my local virtualenv is 3.12.

**Comment by ml31415** [comment]
@limx0 how about relying on `ruff` for unused imports? It's currently checked twice anyways I suppose.
https://docs.astral.sh/ruff/rules/unused-import/

**Pull request merged**
