### PR TITLE
Add python 3.13 CI

### PR DESCRIPTION
**Pull request by ml31415**

### CODE REVIEW

**Comment by ml31415** [comment]
Looks like we need to wait for https://github.com/jcrist/msgspec/issues/698

**Comment by ml31415** [comment]
@limx0 ready for merge I guess.

**Review by limx0 — APPROVED** [review]

**Comment by limx0** [comment]
Thanks @ml31415 !

**Comment by ml31415** [comment]
@limx0 I'd suggest a new release, so that the 3.13 compatibility is visible on pypi.

**Pull request merged**
